import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Footer from "@/components/Layout/Footer";
import Providers from "@/components/Layout/Provider";
import { NextIntlClientProvider } from "next-intl";
import AuthLoader from "@/components/Modal/AuthLoader";
import ConditionalWrapper from "@/components/Layout/ConditionalWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="tr">
      <body className={`${geistSans.variable} ${geistMono.variable} bg-white`}>
        <NextIntlClientProvider locale="tr">
          <Providers>
            <AuthLoader />
            <ConditionalWrapper>{children}</ConditionalWrapper>
            <AuthLoader />
          </Providers>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
